---
# tasks file for purefa
- name: Collect array information
  purestorage.flasharray.purefa_info:
    gather_subset:
      - minimum
      - config
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  register: array_info

- name: Manage array name
  purestorage.flasharray.purefa_arrayname:
    name: "{{ purefa_array_name }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  when: purefa_array_name is defined
  tags:
  - purefa_array_name

- name: Manage Phonehome
  purestorage.flasharray.purefa_phonehome:
    state: "{{ purefa_phonehome_state }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  when: purefa_phonehome_state is defined
  tags:
  - purefa_phonehome

- name: Manage Remote Assist port
  purestorage.flasharray.purefa_ra:
    state: "{{ purefa_remote_assist_state }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  when: purefa_remote_assist_state is defined
  tags:
  - purefa_ra

- name: Set NTP server addresses
  purestorage.flasharray.purefa_ntp:
    state: "{{ 'present' if purefa_ntp_servers else 'absent' }}"
    ntp_servers: "{{ purefa_ntp_servers }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  when: purefa_ntp_servers is defined
  tags:
  - purefa_ntp

- name: Set DNS server addresses
  purestorage.flasharray.purefa_dns:
    state: "{{ 'present' if purefa_dns_servers else 'absent' }}"
    domain: "{{ purefa_domain | default(omit) }}"
    nameservers: "{{ purefa_dns_servers }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  when: purefa_dns_servers is defined
  tags:
  - purefa_dns

- name: Manage local users
  purestorage.flasharray.purefa_user:
    name: "{{ item.name }}"
    password: "{{ item.password}}"
    old_password: "{{ item.old_password | default(omit) }}"
    role: "{{ item.role | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  loop: "{{ purefa_users }}"
  when: purefa_users is defined
  tags:
  - purefa_users

- name: Manage directory service
  include_tasks: directory_service.yml
  when: purefa_ldap is defined
  tags:
  - purefa_ldap

# module is not idempotent
- name: Manage v2c SNMP manager
  purestorage.flasharray.purefa_snmp:
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name }}"
    community: "{{ item.community }}"
    host: "{{ item.host }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  loop: "{{ purefa_snmp }}"
  when: purefa_snmp is defined
  tags:
  - purefa_snmp

- name: Set array syslog servers
  purestorage.flasharray.purefa_syslog:
    state: "{{ purefa_syslog.state | default('present')}}"
    address: "{{ purefa_syslog.address }}"
    port: "{{ purefa_syslog.port }}"
    protocol: "{{ purefa_syslog.protocol }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  when: purefa_syslog is defined
  tags:
  - purefa_syslog

- name: Set SMTP settings
  purestorage.flasharray.purefa_smtp:
    state: "{{ 'present' if purefa_smtp else 'absent' }}"
    sender_domain: "{{ purefa_domain }}"
    password: "{{ purefa_smtp.password }}"
    user: "{{ purefa_smtp.user }}"
    relay_host: "{{ purefa_smtp.relay_host }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  when: purefa_smtp is defined
  tags:
  - purefa_smtp

- name: Manage email recipients alerts
  purestorage.flasharray.purefa_alert:
    address: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  loop: "{{ purefa_alerts }}"
  # smtp config need to be different to run (module isnt idempotent)
  when: item not in array_info.purefa_info.config.smtp
  tags:
  - purefa_alerts

- name: Manage replication connections
  purestorage.flasharray.purefa_connect:
    connection: "{{ item.connection | default('async') }}"
    target_url: "{{ item.target_url }}"
    target_api: "{{ item.target_api }}"
    state: "{{ item.state | default('present') }}"
    fa_url: "{{ purefa_url }}"
    api_token: "{{ purefa_api_token }}"
  loop: "{{ purefa_connections }}"
  when: purefa_connections is defined
  tags:
  - purefa_connections
